#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : rubygem-guard-rspec
Version  : 4.6.3
Release  : 8
URL      : https://rubygems.org/downloads/guard-rspec-4.6.3.gem
Source0  : https://rubygems.org/downloads/guard-rspec-4.6.3.gem
Summary  : No detailed summary available
Group    : Development/Tools
License  : MIT
BuildRequires : ruby
BuildRequires : rubygem-addressable
BuildRequires : rubygem-devise
BuildRequires : rubygem-diff-lcs
BuildRequires : rubygem-guard-compat
BuildRequires : rubygem-launchy
BuildRequires : rubygem-rdoc
BuildRequires : rubygem-rspec
BuildRequires : rubygem-rspec-core
BuildRequires : rubygem-rspec-expectations
BuildRequires : rubygem-rspec-mocks
BuildRequires : rubygem-rspec-support

%description
# Guard::RSpec
[![Gem Version](https://badge.fury.io/rb/guard-rspec.png)](http://badge.fury.io/rb/guard-rspec) [![Build Status](https://secure.travis-ci.org/guard/guard-rspec.png?branch=master)](http://travis-ci.org/guard/guard-rspec) [![Dependency Status](https://gemnasium.com/guard/guard-rspec.png)](https://gemnasium.com/guard/guard-rspec) [![Code Climate](https://codeclimate.com/github/guard/guard-rspec.png)](https://codeclimate.com/github/guard/guard-rspec) [![Coverage Status](https://coveralls.io/repos/guard/guard-rspec/badge.png?branch=master)](https://coveralls.io/r/guard/guard-rspec)

%prep
gem unpack %{SOURCE0}
%setup -q -D -T -n guard-rspec-4.6.3
gem spec %{SOURCE0} -l --ruby > rubygem-guard-rspec.gemspec

%build
gem build rubygem-guard-rspec.gemspec

%install
%global gem_dir $(ruby -e'puts Gem.default_dir')
gem install -V \
--local \
--force \
--install-dir .%{gem_dir} \
--bindir .%{_bindir} \
guard-rspec-4.6.3.gem

mkdir -p %{buildroot}%{gem_dir}
cp -pa .%{gem_dir}/* \
%{buildroot}%{gem_dir}

if [ -d .%{_bindir} ]; then
mkdir -p %{buildroot}%{_bindir}
cp -pa .%{_bindir}/* \
%{buildroot}%{_bindir}/
fi

%check
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost
pushd %{buildroot}%{gem_dir}/gems/guard-rspec-4.6.3
rspec -I.:lib spec/
popd


%files
%defattr(-,root,root,-)
/usr/lib64/ruby/gems/2.2.0/cache/guard-rspec-4.6.3.gem
/usr/lib64/ruby/gems/2.2.0/doc/guard-rspec-4.6.3/ri/Guard/RSpec/Command/_cmd_include_formatter%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/guard-rspec-4.6.3/ri/Guard/RSpec/Command/_guard_formatter-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/guard-rspec-4.6.3/ri/Guard/RSpec/Command/_parts-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/guard-rspec-4.6.3/ri/Guard/RSpec/Command/_paths-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/guard-rspec-4.6.3/ri/Guard/RSpec/Command/_rspec_formatters-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/guard-rspec-4.6.3/ri/Guard/RSpec/Command/_visual_formatter-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/guard-rspec-4.6.3/ri/Guard/RSpec/Command/cdesc-Command.ri
/usr/lib64/ruby/gems/2.2.0/doc/guard-rspec-4.6.3/ri/Guard/RSpec/Command/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/guard-rspec-4.6.3/ri/Guard/RSpec/Command/options-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/guard-rspec-4.6.3/ri/Guard/RSpec/Command/paths-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/guard-rspec-4.6.3/ri/Guard/RSpec/Core/cdesc-Core.ri
/usr/lib64/ruby/gems/2.2.0/doc/guard-rspec-4.6.3/ri/Guard/RSpec/Deprecator/_deprecated-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/guard-rspec-4.6.3/ri/Guard/RSpec/Deprecator/_exclude_option-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/guard-rspec-4.6.3/ri/Guard/RSpec/Deprecator/_focus_on_failed_option-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/guard-rspec-4.6.3/ri/Guard/RSpec/Deprecator/_keep_failed_option-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/guard-rspec-4.6.3/ri/Guard/RSpec/Deprecator/_spec_opts_env-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/guard-rspec-4.6.3/ri/Guard/RSpec/Deprecator/_use_cmd_option-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/guard-rspec-4.6.3/ri/Guard/RSpec/Deprecator/_version_option-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/guard-rspec-4.6.3/ri/Guard/RSpec/Deprecator/cdesc-Deprecator.ri
/usr/lib64/ruby/gems/2.2.0/doc/guard-rspec-4.6.3/ri/Guard/RSpec/Deprecator/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/guard-rspec-4.6.3/ri/Guard/RSpec/Deprecator/options-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/guard-rspec-4.6.3/ri/Guard/RSpec/Deprecator/warns_about_deprecated_options-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/guard-rspec-4.6.3/ri/Guard/RSpec/Deprecator/warns_about_deprecated_options-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/guard-rspec-4.6.3/ri/Guard/RSpec/Dsl/_view_extensions-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/guard-rspec-4.6.3/ri/Guard/RSpec/Dsl/cdesc-Dsl.ri
/usr/lib64/ruby/gems/2.2.0/doc/guard-rspec-4.6.3/ri/Guard/RSpec/Dsl/detect_spec_file_for-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/guard-rspec-4.6.3/ri/Guard/RSpec/Dsl/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/guard-rspec-4.6.3/ri/Guard/RSpec/Dsl/rails-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/guard-rspec-4.6.3/ri/Guard/RSpec/Dsl/rspec-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/guard-rspec-4.6.3/ri/Guard/RSpec/Dsl/ruby-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/guard-rspec-4.6.3/ri/Guard/RSpec/Dsl/watch_spec_files_for-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/guard-rspec-4.6.3/ri/Guard/RSpec/Inspectors/BaseInspector/_clean-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/guard-rspec-4.6.3/ri/Guard/RSpec/Inspectors/BaseInspector/_collect_files-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/guard-rspec-4.6.3/ri/Guard/RSpec/Inspectors/BaseInspector/_paths_with_chdir-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/guard-rspec-4.6.3/ri/Guard/RSpec/Inspectors/BaseInspector/_select_only_spec_dirs-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/guard-rspec-4.6.3/ri/Guard/RSpec/Inspectors/BaseInspector/_select_only_spec_files-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/guard-rspec-4.6.3/ri/Guard/RSpec/Inspectors/BaseInspector/_spec_paths_with_chdir-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/guard-rspec-4.6.3/ri/Guard/RSpec/Inspectors/BaseInspector/cdesc-BaseInspector.ri
/usr/lib64/ruby/gems/2.2.0/doc/guard-rspec-4.6.3/ri/Guard/RSpec/Inspectors/BaseInspector/failed-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/guard-rspec-4.6.3/ri/Guard/RSpec/Inspectors/BaseInspector/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/guard-rspec-4.6.3/ri/Guard/RSpec/Inspectors/BaseInspector/options-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/guard-rspec-4.6.3/ri/Guard/RSpec/Inspectors/BaseInspector/paths-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/guard-rspec-4.6.3/ri/Guard/RSpec/Inspectors/BaseInspector/reload-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/guard-rspec-4.6.3/ri/Guard/RSpec/Inspectors/BaseInspector/spec_paths-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/guard-rspec-4.6.3/ri/Guard/RSpec/Inspectors/Factory/cdesc-Factory.ri
/usr/lib64/ruby/gems/2.2.0/doc/guard-rspec-4.6.3/ri/Guard/RSpec/Inspectors/Factory/create-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/guard-rspec-4.6.3/ri/Guard/RSpec/Inspectors/FocusedInspector/cdesc-FocusedInspector.ri
/usr/lib64/ruby/gems/2.2.0/doc/guard-rspec-4.6.3/ri/Guard/RSpec/Inspectors/FocusedInspector/failed-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/guard-rspec-4.6.3/ri/Guard/RSpec/Inspectors/FocusedInspector/focused_locations-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/guard-rspec-4.6.3/ri/Guard/RSpec/Inspectors/FocusedInspector/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/guard-rspec-4.6.3/ri/Guard/RSpec/Inspectors/FocusedInspector/paths-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/guard-rspec-4.6.3/ri/Guard/RSpec/Inspectors/FocusedInspector/reload-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/guard-rspec-4.6.3/ri/Guard/RSpec/Inspectors/KeepingInspector/_location_path-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/guard-rspec-4.6.3/ri/Guard/RSpec/Inspectors/KeepingInspector/_with_failed_locations-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/guard-rspec-4.6.3/ri/Guard/RSpec/Inspectors/KeepingInspector/cdesc-KeepingInspector.ri
/usr/lib64/ruby/gems/2.2.0/doc/guard-rspec-4.6.3/ri/Guard/RSpec/Inspectors/KeepingInspector/failed-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/guard-rspec-4.6.3/ri/Guard/RSpec/Inspectors/KeepingInspector/failed_locations-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/guard-rspec-4.6.3/ri/Guard/RSpec/Inspectors/KeepingInspector/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/guard-rspec-4.6.3/ri/Guard/RSpec/Inspectors/KeepingInspector/paths-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/guard-rspec-4.6.3/ri/Guard/RSpec/Inspectors/KeepingInspector/reload-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/guard-rspec-4.6.3/ri/Guard/RSpec/Inspectors/SimpleInspector/cdesc-SimpleInspector.ri
/usr/lib64/ruby/gems/2.2.0/doc/guard-rspec-4.6.3/ri/Guard/RSpec/Inspectors/SimpleInspector/failed-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/guard-rspec-4.6.3/ri/Guard/RSpec/Inspectors/SimpleInspector/paths-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/guard-rspec-4.6.3/ri/Guard/RSpec/Inspectors/SimpleInspector/reload-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/guard-rspec-4.6.3/ri/Guard/RSpec/Inspectors/cdesc-Inspectors.ri
/usr/lib64/ruby/gems/2.2.0/doc/guard-rspec-4.6.3/ri/Guard/RSpec/Notifier/_image-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/guard-rspec-4.6.3/ri/Guard/RSpec/Notifier/_parse_summary-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/guard-rspec-4.6.3/ri/Guard/RSpec/Notifier/_priority-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/guard-rspec-4.6.3/ri/Guard/RSpec/Notifier/cdesc-Notifier.ri
/usr/lib64/ruby/gems/2.2.0/doc/guard-rspec-4.6.3/ri/Guard/RSpec/Notifier/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/guard-rspec-4.6.3/ri/Guard/RSpec/Notifier/notify-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/guard-rspec-4.6.3/ri/Guard/RSpec/Notifier/notify_failure-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/guard-rspec-4.6.3/ri/Guard/RSpec/Notifier/options-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/guard-rspec-4.6.3/ri/Guard/RSpec/Options/_deep_merge-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/guard-rspec-4.6.3/ri/Guard/RSpec/Options/cdesc-Options.ri
/usr/lib64/ruby/gems/2.2.0/doc/guard-rspec-4.6.3/ri/Guard/RSpec/Options/with_defaults-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/guard-rspec-4.6.3/ri/Guard/RSpec/RSpecProcess/Failure/cdesc-Failure.ri
/usr/lib64/ruby/gems/2.2.0/doc/guard-rspec-4.6.3/ri/Guard/RSpec/RSpecProcess/_read_results-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/guard-rspec-4.6.3/ri/Guard/RSpec/RSpecProcess/_really_run-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/guard-rspec-4.6.3/ri/Guard/RSpec/RSpecProcess/_run-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/guard-rspec-4.6.3/ri/Guard/RSpec/RSpecProcess/_without_bundler_env-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/guard-rspec-4.6.3/ri/Guard/RSpec/RSpecProcess/all_green%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/guard-rspec-4.6.3/ri/Guard/RSpec/RSpecProcess/cdesc-RSpecProcess.ri
/usr/lib64/ruby/gems/2.2.0/doc/guard-rspec-4.6.3/ri/Guard/RSpec/RSpecProcess/command-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/guard-rspec-4.6.3/ri/Guard/RSpec/RSpecProcess/exit_code-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/guard-rspec-4.6.3/ri/Guard/RSpec/RSpecProcess/formatter_tmp_file-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/guard-rspec-4.6.3/ri/Guard/RSpec/RSpecProcess/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/guard-rspec-4.6.3/ri/Guard/RSpec/RSpecProcess/results-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/guard-rspec-4.6.3/ri/Guard/RSpec/Results/InvalidData/cdesc-InvalidData.ri
/usr/lib64/ruby/gems/2.2.0/doc/guard-rspec-4.6.3/ri/Guard/RSpec/Results/cdesc-Results.ri
/usr/lib64/ruby/gems/2.2.0/doc/guard-rspec-4.6.3/ri/Guard/RSpec/Results/failed_paths-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/guard-rspec-4.6.3/ri/Guard/RSpec/Results/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/guard-rspec-4.6.3/ri/Guard/RSpec/Results/summary-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/guard-rspec-4.6.3/ri/Guard/RSpec/Runner/NoCmdOptionError/cdesc-NoCmdOptionError.ri
/usr/lib64/ruby/gems/2.2.0/doc/guard-rspec-4.6.3/ri/Guard/RSpec/Runner/NoCmdOptionError/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/guard-rspec-4.6.3/ri/Guard/RSpec/Runner/_open_launchy-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/guard-rspec-4.6.3/ri/Guard/RSpec/Runner/_really_run-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/guard-rspec-4.6.3/ri/Guard/RSpec/Runner/_results_file-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/guard-rspec-4.6.3/ri/Guard/RSpec/Runner/_run-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/guard-rspec-4.6.3/ri/Guard/RSpec/Runner/cdesc-Runner.ri
/usr/lib64/ruby/gems/2.2.0/doc/guard-rspec-4.6.3/ri/Guard/RSpec/Runner/inspector-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/guard-rspec-4.6.3/ri/Guard/RSpec/Runner/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/guard-rspec-4.6.3/ri/Guard/RSpec/Runner/notifier-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/guard-rspec-4.6.3/ri/Guard/RSpec/Runner/options-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/guard-rspec-4.6.3/ri/Guard/RSpec/Runner/reload-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/guard-rspec-4.6.3/ri/Guard/RSpec/Runner/run-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/guard-rspec-4.6.3/ri/Guard/RSpec/Runner/run_all-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/guard-rspec-4.6.3/ri/Guard/RSpec/_throw_if_failed-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/guard-rspec-4.6.3/ri/Guard/RSpec/cdesc-RSpec.ri
/usr/lib64/ruby/gems/2.2.0/doc/guard-rspec-4.6.3/ri/Guard/RSpec/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/guard-rspec-4.6.3/ri/Guard/RSpec/options-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/guard-rspec-4.6.3/ri/Guard/RSpec/reload-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/guard-rspec-4.6.3/ri/Guard/RSpec/run_all-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/guard-rspec-4.6.3/ri/Guard/RSpec/run_on_modifications-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/guard-rspec-4.6.3/ri/Guard/RSpec/runner-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/guard-rspec-4.6.3/ri/Guard/RSpec/start-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/guard-rspec-4.6.3/ri/Guard/RSpecDefaults/cdesc-RSpecDefaults.ri
/usr/lib64/ruby/gems/2.2.0/doc/guard-rspec-4.6.3/ri/Guard/RSpecFormatter/Error/UnsupportedPattern/cdesc-UnsupportedPattern.ri
/usr/lib64/ruby/gems/2.2.0/doc/guard-rspec-4.6.3/ri/Guard/RSpecFormatter/Error/UnsupportedPattern/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/guard-rspec-4.6.3/ri/Guard/RSpecFormatter/Error/cdesc-Error.ri
/usr/lib64/ruby/gems/2.2.0/doc/guard-rspec-4.6.3/ri/Guard/RSpecFormatter/_failed_paths-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/guard-rspec-4.6.3/ri/Guard/RSpecFormatter/_message-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/guard-rspec-4.6.3/ri/Guard/RSpecFormatter/_results_file-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/guard-rspec-4.6.3/ri/Guard/RSpecFormatter/_status_failed%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/guard-rspec-4.6.3/ri/Guard/RSpecFormatter/_write-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/guard-rspec-4.6.3/ri/Guard/RSpecFormatter/cdesc-RSpecFormatter.ri
/usr/lib64/ruby/gems/2.2.0/doc/guard-rspec-4.6.3/ri/Guard/RSpecFormatter/dump_summary-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/guard-rspec-4.6.3/ri/Guard/RSpecFormatter/example_failed-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/guard-rspec-4.6.3/ri/Guard/RSpecFormatter/examples-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/guard-rspec-4.6.3/ri/Guard/RSpecFormatter/extract_spec_location-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/guard-rspec-4.6.3/ri/Guard/RSpecFormatter/rspec_3%3f-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/guard-rspec-4.6.3/ri/Guard/RSpecFormatter/spec_path%3f-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/guard-rspec-4.6.3/ri/Guard/RSpecFormatter/write_summary-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/guard-rspec-4.6.3/ri/Guard/RSpecVersion/cdesc-RSpecVersion.ri
/usr/lib64/ruby/gems/2.2.0/doc/guard-rspec-4.6.3/ri/Guard/cdesc-Guard.ri
/usr/lib64/ruby/gems/2.2.0/doc/guard-rspec-4.6.3/ri/cache.ri
/usr/lib64/ruby/gems/2.2.0/doc/guard-rspec-4.6.3/ri/lib/guard/rspec/templates/page-Guardfile.ri
/usr/lib64/ruby/gems/2.2.0/gems/guard-rspec-4.6.3/.gitignore
/usr/lib64/ruby/gems/2.2.0/gems/guard-rspec-4.6.3/.hound.yml
/usr/lib64/ruby/gems/2.2.0/gems/guard-rspec-4.6.3/.rspec
/usr/lib64/ruby/gems/2.2.0/gems/guard-rspec-4.6.3/.rubocop.yml
/usr/lib64/ruby/gems/2.2.0/gems/guard-rspec-4.6.3/.rubocop_todo.yml
/usr/lib64/ruby/gems/2.2.0/gems/guard-rspec-4.6.3/.travis.yml
/usr/lib64/ruby/gems/2.2.0/gems/guard-rspec-4.6.3/CONTRIBUTING.md
/usr/lib64/ruby/gems/2.2.0/gems/guard-rspec-4.6.3/Gemfile
/usr/lib64/ruby/gems/2.2.0/gems/guard-rspec-4.6.3/Guardfile
/usr/lib64/ruby/gems/2.2.0/gems/guard-rspec-4.6.3/LICENSE.txt
/usr/lib64/ruby/gems/2.2.0/gems/guard-rspec-4.6.3/README.md
/usr/lib64/ruby/gems/2.2.0/gems/guard-rspec-4.6.3/Rakefile
/usr/lib64/ruby/gems/2.2.0/gems/guard-rspec-4.6.3/gemfiles/Gemfile.rspec-2.14
/usr/lib64/ruby/gems/2.2.0/gems/guard-rspec-4.6.3/gemfiles/Gemfile.rspec-2.99
/usr/lib64/ruby/gems/2.2.0/gems/guard-rspec-4.6.3/gemfiles/Gemfile.rspec-3.3
/usr/lib64/ruby/gems/2.2.0/gems/guard-rspec-4.6.3/guard-rspec.gemspec
/usr/lib64/ruby/gems/2.2.0/gems/guard-rspec-4.6.3/lib/guard/rspec.rb
/usr/lib64/ruby/gems/2.2.0/gems/guard-rspec-4.6.3/lib/guard/rspec/command.rb
/usr/lib64/ruby/gems/2.2.0/gems/guard-rspec-4.6.3/lib/guard/rspec/deprecator.rb
/usr/lib64/ruby/gems/2.2.0/gems/guard-rspec-4.6.3/lib/guard/rspec/dsl.rb
/usr/lib64/ruby/gems/2.2.0/gems/guard-rspec-4.6.3/lib/guard/rspec/inspectors/base_inspector.rb
/usr/lib64/ruby/gems/2.2.0/gems/guard-rspec-4.6.3/lib/guard/rspec/inspectors/factory.rb
/usr/lib64/ruby/gems/2.2.0/gems/guard-rspec-4.6.3/lib/guard/rspec/inspectors/focused_inspector.rb
/usr/lib64/ruby/gems/2.2.0/gems/guard-rspec-4.6.3/lib/guard/rspec/inspectors/keeping_inspector.rb
/usr/lib64/ruby/gems/2.2.0/gems/guard-rspec-4.6.3/lib/guard/rspec/inspectors/simple_inspector.rb
/usr/lib64/ruby/gems/2.2.0/gems/guard-rspec-4.6.3/lib/guard/rspec/notifier.rb
/usr/lib64/ruby/gems/2.2.0/gems/guard-rspec-4.6.3/lib/guard/rspec/options.rb
/usr/lib64/ruby/gems/2.2.0/gems/guard-rspec-4.6.3/lib/guard/rspec/results.rb
/usr/lib64/ruby/gems/2.2.0/gems/guard-rspec-4.6.3/lib/guard/rspec/rspec_process.rb
/usr/lib64/ruby/gems/2.2.0/gems/guard-rspec-4.6.3/lib/guard/rspec/runner.rb
/usr/lib64/ruby/gems/2.2.0/gems/guard-rspec-4.6.3/lib/guard/rspec/templates/Guardfile
/usr/lib64/ruby/gems/2.2.0/gems/guard-rspec-4.6.3/lib/guard/rspec/version.rb
/usr/lib64/ruby/gems/2.2.0/gems/guard-rspec-4.6.3/lib/guard/rspec_defaults.rb
/usr/lib64/ruby/gems/2.2.0/gems/guard-rspec-4.6.3/lib/guard/rspec_formatter.rb
/usr/lib64/ruby/gems/2.2.0/gems/guard-rspec-4.6.3/spec/lib/guard/rspec/command_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/guard-rspec-4.6.3/spec/lib/guard/rspec/deprecator_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/guard-rspec-4.6.3/spec/lib/guard/rspec/inspectors/base_inspector_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/guard-rspec-4.6.3/spec/lib/guard/rspec/inspectors/factory_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/guard-rspec-4.6.3/spec/lib/guard/rspec/inspectors/focused_inspector_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/guard-rspec-4.6.3/spec/lib/guard/rspec/inspectors/keeping_inspector_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/guard-rspec-4.6.3/spec/lib/guard/rspec/inspectors/shared_examples.rb
/usr/lib64/ruby/gems/2.2.0/gems/guard-rspec-4.6.3/spec/lib/guard/rspec/inspectors/simple_inspector_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/guard-rspec-4.6.3/spec/lib/guard/rspec/notifier_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/guard-rspec-4.6.3/spec/lib/guard/rspec/results_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/guard-rspec-4.6.3/spec/lib/guard/rspec/rspec_process_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/guard-rspec-4.6.3/spec/lib/guard/rspec/runner_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/guard-rspec-4.6.3/spec/lib/guard/rspec/template_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/guard-rspec-4.6.3/spec/lib/guard/rspec_formatter_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/guard-rspec-4.6.3/spec/lib/guard/rspec_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/guard-rspec-4.6.3/spec/spec_helper.rb
/usr/lib64/ruby/gems/2.2.0/specifications/guard-rspec-4.6.3.gemspec
