#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : rubygem-guard-rspec
Version  : 4.6.4
Release  : 11
URL      : https://rubygems.org/downloads/guard-rspec-4.6.4.gem
Source0  : https://rubygems.org/downloads/guard-rspec-4.6.4.gem
Summary  : No detailed summary available
Group    : Development/Tools
License  : MIT
BuildRequires : ruby
BuildRequires : rubygem-addressable
BuildRequires : rubygem-devise
BuildRequires : rubygem-diff-lcs
BuildRequires : rubygem-guard-compat
BuildRequires : rubygem-launchy
BuildRequires : rubygem-rdoc
BuildRequires : rubygem-rspec
BuildRequires : rubygem-rspec-core
BuildRequires : rubygem-rspec-expectations
BuildRequires : rubygem-rspec-mocks
BuildRequires : rubygem-rspec-support

%description
# Guard::RSpec
[![Gem Version](https://badge.fury.io/rb/guard-rspec.png)](http://badge.fury.io/rb/guard-rspec) [![Build Status](https://secure.travis-ci.org/guard/guard-rspec.png?branch=master)](http://travis-ci.org/guard/guard-rspec) [![Dependency Status](https://gemnasium.com/guard/guard-rspec.png)](https://gemnasium.com/guard/guard-rspec) [![Code Climate](https://codeclimate.com/github/guard/guard-rspec.png)](https://codeclimate.com/github/guard/guard-rspec) [![Coverage Status](https://coveralls.io/repos/guard/guard-rspec/badge.png?branch=master)](https://coveralls.io/r/guard/guard-rspec)

%prep
gem unpack %{SOURCE0}
%setup -q -D -T -n guard-rspec-4.6.4
gem spec %{SOURCE0} -l --ruby > rubygem-guard-rspec.gemspec

%build
gem build rubygem-guard-rspec.gemspec

%install
%global gem_dir $(ruby -e'puts Gem.default_dir')
gem install -V \
--local \
--force \
--install-dir .%{gem_dir} \
--bindir .%{_bindir} \
guard-rspec-4.6.4.gem

mkdir -p %{buildroot}%{gem_dir}
cp -pa .%{gem_dir}/* \
%{buildroot}%{gem_dir}

if [ -d .%{_bindir} ]; then
mkdir -p %{buildroot}%{_bindir}
cp -pa .%{_bindir}/* \
%{buildroot}%{_bindir}/
fi

%check
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost
pushd %{buildroot}%{gem_dir}/gems/guard-rspec-4.6.4
rspec -I.:lib spec/
popd


%files
%defattr(-,root,root,-)
/usr/lib64/ruby/gems/2.3.0/cache/guard-rspec-4.6.4.gem
/usr/lib64/ruby/gems/2.3.0/gems/guard-rspec-4.6.4/.gitignore
/usr/lib64/ruby/gems/2.3.0/gems/guard-rspec-4.6.4/.hound.yml
/usr/lib64/ruby/gems/2.3.0/gems/guard-rspec-4.6.4/.rspec
/usr/lib64/ruby/gems/2.3.0/gems/guard-rspec-4.6.4/.rubocop.yml
/usr/lib64/ruby/gems/2.3.0/gems/guard-rspec-4.6.4/.rubocop_todo.yml
/usr/lib64/ruby/gems/2.3.0/gems/guard-rspec-4.6.4/.travis.yml
/usr/lib64/ruby/gems/2.3.0/gems/guard-rspec-4.6.4/CONTRIBUTING.md
/usr/lib64/ruby/gems/2.3.0/gems/guard-rspec-4.6.4/Gemfile
/usr/lib64/ruby/gems/2.3.0/gems/guard-rspec-4.6.4/Guardfile
/usr/lib64/ruby/gems/2.3.0/gems/guard-rspec-4.6.4/LICENSE.txt
/usr/lib64/ruby/gems/2.3.0/gems/guard-rspec-4.6.4/README.md
/usr/lib64/ruby/gems/2.3.0/gems/guard-rspec-4.6.4/Rakefile
/usr/lib64/ruby/gems/2.3.0/gems/guard-rspec-4.6.4/gemfiles/Gemfile.rspec-2.14
/usr/lib64/ruby/gems/2.3.0/gems/guard-rspec-4.6.4/gemfiles/Gemfile.rspec-2.99
/usr/lib64/ruby/gems/2.3.0/gems/guard-rspec-4.6.4/gemfiles/Gemfile.rspec-3.3
/usr/lib64/ruby/gems/2.3.0/gems/guard-rspec-4.6.4/guard-rspec.gemspec
/usr/lib64/ruby/gems/2.3.0/gems/guard-rspec-4.6.4/lib/guard/rspec.rb
/usr/lib64/ruby/gems/2.3.0/gems/guard-rspec-4.6.4/lib/guard/rspec/command.rb
/usr/lib64/ruby/gems/2.3.0/gems/guard-rspec-4.6.4/lib/guard/rspec/deprecator.rb
/usr/lib64/ruby/gems/2.3.0/gems/guard-rspec-4.6.4/lib/guard/rspec/dsl.rb
/usr/lib64/ruby/gems/2.3.0/gems/guard-rspec-4.6.4/lib/guard/rspec/inspectors/base_inspector.rb
/usr/lib64/ruby/gems/2.3.0/gems/guard-rspec-4.6.4/lib/guard/rspec/inspectors/factory.rb
/usr/lib64/ruby/gems/2.3.0/gems/guard-rspec-4.6.4/lib/guard/rspec/inspectors/focused_inspector.rb
/usr/lib64/ruby/gems/2.3.0/gems/guard-rspec-4.6.4/lib/guard/rspec/inspectors/keeping_inspector.rb
/usr/lib64/ruby/gems/2.3.0/gems/guard-rspec-4.6.4/lib/guard/rspec/inspectors/simple_inspector.rb
/usr/lib64/ruby/gems/2.3.0/gems/guard-rspec-4.6.4/lib/guard/rspec/notifier.rb
/usr/lib64/ruby/gems/2.3.0/gems/guard-rspec-4.6.4/lib/guard/rspec/options.rb
/usr/lib64/ruby/gems/2.3.0/gems/guard-rspec-4.6.4/lib/guard/rspec/results.rb
/usr/lib64/ruby/gems/2.3.0/gems/guard-rspec-4.6.4/lib/guard/rspec/rspec_process.rb
/usr/lib64/ruby/gems/2.3.0/gems/guard-rspec-4.6.4/lib/guard/rspec/runner.rb
/usr/lib64/ruby/gems/2.3.0/gems/guard-rspec-4.6.4/lib/guard/rspec/templates/Guardfile
/usr/lib64/ruby/gems/2.3.0/gems/guard-rspec-4.6.4/lib/guard/rspec/version.rb
/usr/lib64/ruby/gems/2.3.0/gems/guard-rspec-4.6.4/lib/guard/rspec_defaults.rb
/usr/lib64/ruby/gems/2.3.0/gems/guard-rspec-4.6.4/lib/guard/rspec_formatter.rb
/usr/lib64/ruby/gems/2.3.0/gems/guard-rspec-4.6.4/spec/lib/guard/rspec/command_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/guard-rspec-4.6.4/spec/lib/guard/rspec/deprecator_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/guard-rspec-4.6.4/spec/lib/guard/rspec/inspectors/base_inspector_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/guard-rspec-4.6.4/spec/lib/guard/rspec/inspectors/factory_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/guard-rspec-4.6.4/spec/lib/guard/rspec/inspectors/focused_inspector_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/guard-rspec-4.6.4/spec/lib/guard/rspec/inspectors/keeping_inspector_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/guard-rspec-4.6.4/spec/lib/guard/rspec/inspectors/shared_examples.rb
/usr/lib64/ruby/gems/2.3.0/gems/guard-rspec-4.6.4/spec/lib/guard/rspec/inspectors/simple_inspector_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/guard-rspec-4.6.4/spec/lib/guard/rspec/notifier_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/guard-rspec-4.6.4/spec/lib/guard/rspec/results_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/guard-rspec-4.6.4/spec/lib/guard/rspec/rspec_process_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/guard-rspec-4.6.4/spec/lib/guard/rspec/runner_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/guard-rspec-4.6.4/spec/lib/guard/rspec/template_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/guard-rspec-4.6.4/spec/lib/guard/rspec_formatter_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/guard-rspec-4.6.4/spec/lib/guard/rspec_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/guard-rspec-4.6.4/spec/spec_helper.rb
/usr/lib64/ruby/gems/2.3.0/specifications/guard-rspec-4.6.4.gemspec
